packageExtensions:
  debug@*:
    dependencies:
      supports-color: "*"
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: "*"
  vue-loader@*:
    peerDependencies:
      '@vue/compiler-sfc': '*'
      'webpack': '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-2.4.1.cjs
